PATCH http://localhost:3000/api/v1/book/f5c31fa2-7fec-44c6-80d3-8b00930a8558
Content-Type: application/json

{
  "isbn": 9780751548556,
  "title": "The Lucky One",
  "author": "Nicholas Sparks",
  "summary": "Hello, The Lucky One",
  "image":"http://s.s-bol.com/imgbase0/imagebase/large/FC/7/0/3/7/1001004011797307.jpg",
  "price": {
    "currency": "MXN",
    "value": 9.8,
    "displayValue": "9.80"
  }
}